// Assignment templates library for AgriSkills Academy
// 15+ ready-to-use scenarios covering all aspects of sheep nutrition

export type TemplateDefinition = {
  title: string;
  description: string;
  category: "gestation" | "lactation" | "croissance" | "engrais" | "general";
  difficulty: "easy" | "normal" | "hard" | "expert";
  animalCategory: string;
  maxCostPerDay: number | null;
  minPDICoverage: number;
  minUFLCoverage: number;
  minPabsCoverage: number | null;
  minCaabsCoverage: number | null;
  maxConcentratePct: number | null;
  weightCost: number;
  weightCoverage: number;
  weightFeasibility: number;
  estimatedTime: number; // minutes
  learningObjectives: string[];
};

export const TEMPLATES: TemplateDefinition[] = [
  // ---------- EASY ----------
  {
    title: "Brebis vide — entretien",
    description: "Formulez une ration d'entretien pour des brebis taries de 70 kg. Objectif: couvrir les besoins minimum au moindre coût.",
    category: "general",
    difficulty: "easy",
    animalCategory: "Brebis  70 kg   Vide",
    maxCostPerDay: 0.50,
    minPDICoverage: 90,
    minUFLCoverage: 90,
    minPabsCoverage: 85,
    minCaabsCoverage: 85,
    maxConcentratePct: 30,
    weightCost: 50,
    weightCoverage: 30,
    weightFeasibility: 20,
    estimatedTime: 15,
    learningObjectives: [
      "Identifier les besoins d'entretien d'une brebis tarie",
      "Choisir un fourrage adapté et économique",
      "Vérifier la couverture des besoins minimum",
    ],
  },
  {
    title: "Brebis gestante — fin de gestation",
    description: "Brebis 70 kg gestante simple, 3 semaines avant agnelage. Besoins accrus en énergie et protéines.",
    category: "gestation",
    difficulty: "easy",
    animalCategory: "Brebis  70 kg   Gestante    Simple      Semaines - 3 à - 4",
    maxCostPerDay: 0.80,
    minPDICoverage: 95,
    minUFLCoverage: 95,
    minPabsCoverage: 90,
    minCaabsCoverage: 90,
    maxConcentratePct: 40,
    weightCost: 35,
    weightCoverage: 45,
    weightFeasibility: 20,
    estimatedTime: 20,
    learningObjectives: [
      "Comprendre l'augmentation des besoins en fin de gestation",
      "Équilibrer énergie (UFL) et protéines (PDI)",
      "Prévenir la toxémie de gestation",
    ],
  },
  {
    title: "Agnelle croissance 40kg",
    description: "Agnelle de renouvellement de 40 kg en croissance. Objectif: croissance régulière sans excès de gras.",
    category: "croissance",
    difficulty: "easy",
    animalCategory: "Agnelle  40 kg   Croissance",
    maxCostPerDay: 0.60,
    minPDICoverage: 95,
    minUFLCoverage: 95,
    minPabsCoverage: 90,
    minCaabsCoverage: 90,
    maxConcentratePct: 50,
    weightCost: 40,
    weightCoverage: 40,
    weightFeasibility: 20,
    estimatedTime: 18,
    learningObjectives: [
      "Formuler pour la croissance des agnelles",
      "Assurer un bon développement osseux (Ca/P)",
      "Préparer la future brebis de renouvellement",
    ],
  },

  // ---------- NORMAL ----------
  {
    title: "Brebis allaitante — début lactation",
    description: "Brebis 70 kg allaitante, semaine 0 à +3 (portée simple). Pic de besoins énergétiques et protéiques.",
    category: "lactation",
    difficulty: "normal",
    animalCategory: "Brebis  70 kg   Allaitante    Simple      Semaines 0 à + 3",
    maxCostPerDay: 1.00,
    minPDICoverage: 95,
    minUFLCoverage: 95,
    minPabsCoverage: 90,
    minCaabsCoverage: 90,
    maxConcentratePct: 50,
    weightCost: 30,
    weightCoverage: 45,
    weightFeasibility: 25,
    estimatedTime: 25,
    learningObjectives: [
      "Couvrir les besoins élevés du début de lactation",
      "Prévenir l'hypocalcémie (fièvre vitulaire)",
      "Maintenir l'état corporel de la brebis",
    ],
  },
  {
    title: "Brebis allaitante — portée double",
    description: "Brebis 70 kg allaitante, portée double, semaine +4 à +6. Production laitière maximale.",
    category: "lactation",
    difficulty: "normal",
    animalCategory: "Brebis  70 kg   Allaitante    Double      Semaines + 4 à + 6",
    maxCostPerDay: 1.20,
    minPDICoverage: 98,
    minUFLCoverage: 98,
    minPabsCoverage: 95,
    minCaabsCoverage: 95,
    maxConcentratePct: 55,
    weightCost: 25,
    weightCoverage: 50,
    weightFeasibility: 25,
    estimatedTime: 30,
    learningObjectives: [
      "Gérer le pic de production laitière avec portée double",
      "Optimiser la densité énergétique de la ration",
      "Éviter le déficit énergétique en début de lactation",
    ],
  },
  {
    title: "Bélier en période de lutte",
    description: "Bélier de 80 kg en période de saillie. Activité intense, besoins énergétiques augmentés.",
    category: "general",
    difficulty: "normal",
    animalCategory: "Bélier  80 kg   Entretien",
    maxCostPerDay: 0.90,
    minPDICoverage: 95,
    minUFLCoverage: 95,
    minPabsCoverage: 90,
    minCaabsCoverage: 90,
    maxConcentratePct: 45,
    weightCost: 35,
    weightCoverage: 40,
    weightFeasibility: 25,
    estimatedTime: 22,
    learningObjectives: [
      "Adapter la ration du bélier en période de reproduction",
      "Maintenir l'état corporel optimal (BCS 3.5-4)",
      "Assurer la fertilité via une bonne nutrition",
    ],
  },
  {
    title: "Agneau engrais 30kg → 40kg",
    description: "Agneau à l'engrais de 30 kg, GMQ 300g/j. Objectif: croissance rapide et rentable.",
    category: "engrais",
    difficulty: "normal",
    animalCategory: "Agnelle  30 kg   Croissance", // Closest available
    maxCostPerDay: 0.70,
    minPDICoverage: 95,
    minUFLCoverage: 95,
    minPabsCoverage: 90,
    minCaabsCoverage: 90,
    maxConcentratePct: 60,
    weightCost: 45,
    weightCoverage: 35,
    weightFeasibility: 20,
    estimatedTime: 25,
    learningObjectives: [
      "Optimiser la croissance de l'agneau à l'engrais",
      "Calculer le coût par kg de gain",
      "Éviter l'acidose avec une ration riche en concentré",
    ],
  },
  {
    title: "Flushing avant saillie",
    description: "Brebis 70 kg, 3 semaines avant saillie. Objectif: améliorer l'ovulation via un apport énergétique accru.",
    category: "gestation",
    difficulty: "normal",
    animalCategory: "Brebis  70 kg   Flushing",
    maxCostPerDay: 0.70,
    minPDICoverage: 90,
    minUFLCoverage: 110, // Practice: flushing = surplus énergétique
    minPabsCoverage: 85,
    minCaabsCoverage: 85,
    maxConcentratePct: 40,
    weightCost: 30,
    weightCoverage: 50,
    weightFeasibility: 20,
    estimatedTime: 20,
    learningObjectives: [
      "Comprendre le principe du flushing",
      "Apporter un surplus énergétique sans excès de protéines",
      "Optimiser le taux d'ovulation",
    ],
  },

  // ---------- HARD ----------
  {
    title: "Gestation double — contrainte coût",
    description: "Brebis 70 kg gestante double, fin de gestation, avec un budget serré de 0.60€/jour. Défi: équilibrer sans dépasser le budget.",
    category: "gestation",
    difficulty: "hard",
    animalCategory: "Brebis  70 kg   Gestante    Double      Semaines - 3 à - 4",
    maxCostPerDay: 0.60,
    minPDICoverage: 95,
    minUFLCoverage: 95,
    minPabsCoverage: 85,
    minCaabsCoverage: 85,
    maxConcentratePct: 45,
    weightCost: 50,
    weightCoverage: 30,
    weightFeasibility: 20,
    estimatedTime: 35,
    learningObjectives: [
      "Optimiser le rapport coût/nutriments",
      "Identifier les aliments les plus économiques",
      "Maintenir la couverture des besoins sous contrainte budgétaire",
    ],
  },
  {
    title: "Transition alimentaire progressive",
    description: "Brebis allaitante passant d'une ration à 60% fourrage à 40% fourrage. Objectif: transition sans acidose sur 1 semaine.",
    category: "lactation",
    difficulty: "hard",
    animalCategory: "Brebis  70 kg   Allaitante    Simple      Semaines + 4 à + 6",
    maxCostPerDay: 1.10,
    minPDICoverage: 95,
    minUFLCoverage: 95,
    minPabsCoverage: 90,
    minCaabsCoverage: 90,
    maxConcentratePct: 60,
    weightCost: 25,
    weightCoverage: 40,
    weightFeasibility: 35,
    estimatedTime: 40,
    learningObjectives: [
      "Comprendre les risques de transition alimentaire",
      "Équilibrer fibres et concentrés pour éviter l'acidose",
      "Maintenir la couverture nutritionnelle pendant la transition",
    ],
  },
  {
    title: "Ration économique avec sous-produits",
    description: "Brebis gestante avec accès à des sous-produits (pulpe de betterave, drêches). Objectif: minimiser le coût en valorisant les sous-produits.",
    category: "gestation",
    difficulty: "hard",
    animalCategory: "Brebis  70 kg   Gestante    Simple      Semaines - 3 à - 4",
    maxCostPerDay: 0.45,
    minPDICoverage: 90,
    minUFLCoverage: 90,
    minPabsCoverage: 80,
    minCaabsCoverage: 80,
    maxConcentratePct: 50,
    weightCost: 55,
    weightCoverage: 25,
    weightFeasibility: 20,
    estimatedTime: 35,
    learningObjectives: [
      "Valoriser les sous-produits dans la ration",
      "Connaître les valeurs nutritives des sous-produits",
      "Équilibrer une ration à faible coût",
    ],
  },

  // ---------- EXPERT ----------
  {
    title: "Multi-lot — gestation + allaitement simultané",
    description: "Le troupeau est divisé: 60% gestantes fin, 40% allaitantes début. Formulez une ration moyenne qui convient aux deux lots.",
    category: "general",
    difficulty: "expert",
    animalCategory: "Brebis  70 kg   Allaitante    Simple      Semaines 0 à + 3",
    maxCostPerDay: 0.90,
    minPDICoverage: 95,
    minUFLCoverage: 95,
    minPabsCoverage: 90,
    minCaabsCoverage: 90,
    maxConcentratePct: 50,
    weightCost: 35,
    weightCoverage: 40,
    weightFeasibility: 25,
    estimatedTime: 45,
    learningObjectives: [
      "Comprendre la complexité de la gestion multi-lot",
      "Trouver un compromis nutritionnel entre stades différents",
      "Anticiper les déficits pour le lot le plus exigeant",
    ],
  },
  {
    title: "Ration bio sans concentré du commerce",
    description: "Brebis allaitante en agriculture biologique. Pas de tourteau de soja importé. Utiliser protéagineux locaux (lupin, féverole, pois).",
    category: "lactation",
    difficulty: "expert",
    animalCategory: "Brebis  70 kg   Allaitante    Simple      Semaines 0 à + 3",
    maxCostPerDay: 1.30,
    minPDICoverage: 95,
    minUFLCoverage: 95,
    minPabsCoverage: 90,
    minCaabsCoverage: 90,
    maxConcentratePct: 55,
    weightCost: 25,
    weightCoverage: 50,
    weightFeasibility: 25,
    estimatedTime: 50,
    learningObjectives: [
      "Formuler une ration 100% locale/bio",
      "Remplacer le soja importé par des protéagineux locaux",
      "Maintenir la couverture protéique sans tourteau de soja",
    ],
  },
  {
    title: "Ration sécheresse — ressources limitées",
    description: "Contexte de sécheresse: foin limité, paille disponible, eau restreinte. Formulez pour 50 brebis gestantes avec ressources minimales.",
    category: "gestation",
    difficulty: "expert",
    animalCategory: "Brebis  70 kg   Gestante    Simple      Semaines - 3 à - 4",
    maxCostPerDay: 0.55,
    minPDICoverage: 85,
    minUFLCoverage: 85,
    minPabsCoverage: 75,
    minCaabsCoverage: 75,
    maxConcentratePct: 65,
    weightCost: 30,
    weightCoverage: 30,
    weightFeasibility: 40,
    estimatedTime: 50,
    learningObjectives: [
      "Adapter la ration en période de sécheresse",
      "Valoriser la paille et les fourrages grossiers",
      "Accepter une couverture réduite sans risque sanitaire",
    ],
  },
  {
    title: "Agneau finisher — maximiser le GMQ",
    description: "Agneau de 35 kg, objectif 400g de GMQ/jour pour marché à 45 kg. Ration haute énergie, risque acidose élevé.",
    category: "engrais",
    difficulty: "expert",
    animalCategory: "Agnelle  40 kg   Croissance",
    maxCostPerDay: 0.80,
    minPDICoverage: 98,
    minUFLCoverage: 110, // surplus pour croissance max
    minPabsCoverage: 95,
    minCaabsCoverage: 95,
    maxConcentratePct: 70,
    weightCost: 30,
    weightCoverage: 40,
    weightFeasibility: 30,
    estimatedTime: 40,
    learningObjectives: [
      "Maximiser le gain quotidien sans acidose",
      "Équilibrer une ration à très haute densité énergétique",
      "Prévenir les risques sanitaires (acidose, calculs urinaires)",
    ],
  },
];

export const CATEGORIES = [
  { id: "gestation", label: "Gestation", color: "bg-blue-100 text-blue-800", icon: "🤰" },
  { id: "lactation", label: "Lactation", color: "bg-emerald-100 text-emerald-800", icon: "🥛" },
  { id: "croissance", label: "Croissance", color: "bg-lime-100 text-lime-800", icon: "🌱" },
  { id: "engrais", label: "Engrais", color: "bg-amber-100 text-amber-800", icon: "🐑" },
  { id: "general", label: "Général", color: "bg-stone-100 text-stone-800", icon: "📚" },
];

export const DIFFICULTIES = [
  { id: "easy", label: "Facile", color: "bg-emerald-100 text-emerald-800", stars: "★" },
  { id: "normal", label: "Normal", color: "bg-blue-100 text-blue-800", stars: "★★" },
  { id: "hard", label: "Difficile", color: "bg-amber-100 text-amber-800", stars: "★★★" },
  { id: "expert", label: "Expert", color: "bg-rose-100 text-rose-800", stars: "★★★★" },
];
